apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-kubernetes-discoveryserver-deployment
spec:
  selector:
    matchLabels:
      app: spring-cloud-kubernetes-discoveryserver
  template:
    metadata:
      labels:
        app: spring-cloud-kubernetes-discoveryserver
    spec:
      containers:
      - name: spring-cloud-kubernetes-discoveryserver
        image: springcloud/spring-cloud-kubernetes-discoveryserver:3.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_KUBERNETES
          value: "DEBUG"
        readinessProbe:
          httpGet:
            port: 8761
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8761
            path: /actuator/health/liveness
        ports:
        - containerPort: 8761