---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: mysql-config-map
    data:
      mysql-server: demo-app-mysql    # The name of mysql service
      mysql-database-name: demoDb     # The name of the database used by the demo app
      mysql-user-username: myUser     # A new created user for the demo app
  - apiVersion: v1
    kind: Secret
    metadata:
      name: mysql-pass
    type: Opaque
    data:
      mysql-root-password: cm9vdHBhc3N3b3Jk       ## rootpassword
      mysql-user-password: dXNlcnBhc3N3b3Jk       ## userpassword
  - apiVersion: v1
    kind: Service
    metadata:
      name: demo-app-mysql
      labels:
        app: demo-app
    spec:
      ports:
        - port: 3306
      selector:
        app: demo-app
        tier: mysql
      clusterIP: None
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql-pvc
      labels:
        app: demo-app
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: mysql-pv
    spec:
      storageClassName:
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: "/mnt/pv1"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-app-mysql
      labels:
        app: demo-app
    spec:
      selector:
        matchLabels:
          app: demo-app
          tier: mysql
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: demo-app
            tier: mysql
        spec:
          containers:
            - image: mysql:5.6
              name: mysql
              env:
                - name: MYSQL_DATABASE
                  valueFrom:
                    configMapKeyRef:
                      name: mysql-config-map
                      key: mysql-database-name
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-pass
                      key: mysql-root-password
                - name: MYSQL_USER
                  valueFrom:
                    configMapKeyRef:
                      name: mysql-config-map
                      key: mysql-user-username
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-pass
                      key: mysql-user-password
              livenessProbe:
                tcpSocket:
                  port: 3306
              ports:
                - containerPort: 3306
                  name: mysql
              volumeMounts:
                - name: mysql-persistent-storage
                  mountPath: /var/lib/mysql
          volumes:
            - name: mysql-persistent-storage
              persistentVolumeClaim:
                claimName: mysql-pvc