#message: "Default msg from props"
spring:
  application:
    name: contact-us-service
  config:
    import: "optional:configserver:"
  main:
    allow-bean-definition-overriding: true


  datasource:
    url: jdbc:mysql://${DB_SERVER}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: '*'
  #  endpoint:
  #    restart:
  #      enabled: true
  #    health:
  #      enabled: true
  #    info:
  #      enabled: true
  #  config:
  #    import: "optional:configserver:"
  #  cloud:
  #    kubernetes:
  #      enabled: false
  #      reload:
  #        enabled: false
  #management:
  #  endpoints:
  #    web:
  #      exposure:
  #        include: '*'
  #eureka:
  #  client:
  #    enabled: true
  #    serviceUrl:
  #      defaultZone: http://localhost:8080/eureka/
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false
#    config:
#      discovery:
#        enabled: true
#        serviceId: config-server
#      label: main
##      fail-fast: true
#      retry:
#        initialInterval: 2000
#        multiplier: 1.5
#        maxInterval: 60000
#        maxAttempts: 100
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
#logging:
#  level:
#    root: debug
#server:
logging:
  level:
    org:
      springframework:
        cloud:
          kubernetes: DEBUG
#  port: 8181

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
    import: configserver:http://spring-cloud-kubernetes-configserver:8888