#message: "Default msg from props"

spring:
  application:
    name: contact-us-service
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
#  config:
#    import: "optional:configserver:"
  #  cloud:
#    kubernetes:
#      enabled: false
#      reload:
#        enabled: false
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false
#    config:
#      discovery:
#        enabled: true
#        serviceId: config-server
#      label: main
##      fail-fast: true
#      retry:
#        initialInterval: 2000
#        multiplier: 1.5
#        maxInterval: 60000
#        maxAttempts: 100
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
#logging:
#  level:
#    root: debug
#server:
#  port: 8181