spring:
  application:
    name: contact-us-service
#  cloud:
#    kubernetes:
#      enabled: false
#      reload:
#        enabled: false
server:
  port: 8181
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/

