eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    maxThreadsForPeerReplication: 0
  service-url:
    defaultZone: http://localhost:8080/eureka
