spring:
  application:
    name: config-server
  cloud:
    kubernetes:
      enabled: false
      reload:
        enabled: false
    config:
      server:
        git:
          # URI of GIT repo containing properties
          uri: https://github.com/MarkizaSckuza/config-server
          default-label: main
          search-paths: configuration
server:
  port: 8585
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka/
logging:
  level:
    root: debug